/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_Principal;
import static java.lang.Thread.sleep;

/**
 *
 * @author Kevin Meza
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**98
     * Creates new form Ventana_Principal
     */
    Controlador_Principal controlador;
    
    public Ventana_Principal() {
        initComponents();
        cargarCreditos();
        setSize(650,250);
        controlador= new Controlador_Principal(this);
        agregarEvento();
        
    }
    
    
    
    
    public void agregarEvento(){
        this.btn_Comenzar.addActionListener(controlador);
    }
    
    
    
    public void cargarCreditos() 
    {
        this.cB_Opciones.removeAllItems();
        
        this.cB_Opciones.addItem("-----Selecciona un metodo de ordenamiento-----");
        this.cB_Opciones.addItem("Metodo Intercambiar");
        this.cB_Opciones.addItem("Metodo Shell");
        this.cB_Opciones.addItem("Metodo Seleccion");
        this.cB_Opciones.addItem("Metodo Quicksort");
        this.cB_Opciones.setSelectedIndex(0);
    }
    
    public String devolverOpcion(){
        String opcion="";
        
        if(this.cB_Opciones.getSelectedIndex()==1){
            
            opcion="Metodo Intercambiar";
            
        }
        if(this.cB_Opciones.getSelectedIndex()==2){
            
            opcion="Metodo Shell";
            
        }
        if(this.cB_Opciones.getSelectedIndex()==3){
            
            opcion="Metodo Seleccion";
            
        }
        if(this.cB_Opciones.getSelectedIndex()==4){
            
            opcion="Metodo Quicksort";
            
        }
        return opcion;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cB_Opciones = new javax.swing.JComboBox<>();
        btn_Comenzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lithos Pro Regular", 3, 24)); // NOI18N
        jLabel1.setText("Metodos de Ordenamiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 6, -1, 39));

        cB_Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cB_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 121, 304, -1));

        btn_Comenzar.setText("Comenzar");
        getContentPane().add(btn_Comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 159, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Bienvenido al este programa de ordenamiento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Para comenzar selecciona un metodo de ordenamiento y aprieta el boton comenzar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 83, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondos_en_color_uniforme.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Comenzar;
    private javax.swing.JComboBox<String> cB_Opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}